### ISSUE TITLE
Cannot be used with burpsuite2024.1 version

### ISSUE THREAD

**Issue by fleabane1** [projectdiscovery/nuclei-burp-plugin#95]
error:
![image](https://github.com/projectdiscovery/nuclei-burp-plugin/assets/58097248/415fece4-d4f3-4dd9-a005-8804ccd1385e)
![image](https://github.com/projectdiscovery/nuclei-burp-plugin/assets/58097248/b9a0f471-7f5e-4a57-aaa0-a3b8c48d4769)
`[11:01:52] Error while trying to initialize the plugin:
java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "definitions" is null
	at io.projectdiscovery.nuclei.util.SchemaUtils.retrieveYamlFieldWithDescriptions(SchemaUtils.java:127)
	at io.projectdiscovery.nuclei.util.SchemaUtils.yamlFieldDescriptionTransformer(SchemaUtils.java:108)
	at io.projectdiscovery.nuclei.util.SchemaUtils.retrieveYamlFieldWithDescriptions(SchemaUtils.java:61)
	at burp.BurpExtender.initializeNucleiYamlSchema(BurpExtender.java:81)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:71)
	at burp.Zhyc.ZW(Unknown Source)
	at burp.Zsxj.Zg(Unknown Source)
	at burp.Zsxu.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)`

Compiling by yourself is not good, like the code needs to be improved, I hope it can be solved, thank you.

**Comment by fleabane1** [comment]
java version "18.0.2.1" 2022-08-18
Java(TM) SE Runtime Environment (build 18.0.2.1+1-1)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)

**Comment by fleabane1** [comment]
> 不是自己编译不行，就是出现了问题

yes

**Comment by GeorginaReeder** [comment]
Thanks for bringing this to our attention @fleabane1 , we'll look into it!
