### ISSUE TITLE
Burp Suite v2023.10.3.2 Error

### ISSUE THREAD

**Issue by badboycxcc** [projectdiscovery/nuclei-burp-plugin#97]
```
[17:32:33] Error while trying to initialize the plugin:
java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "definitions" is null
	at io.projectdiscovery.nuclei.util.SchemaUtils.retrieveYamlFieldWithDescriptions(SchemaUtils.java:127)
	at io.projectdiscovery.nuclei.util.SchemaUtils.yamlFieldDescriptionTransformer(SchemaUtils.java:108)
	at io.projectdiscovery.nuclei.util.SchemaUtils.retrieveYamlFieldWithDescriptions(SchemaUtils.java:61)
	at burp.BurpExtender.initializeNucleiYamlSchema(BurpExtender.java:81)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:71)
	at burp.Zaq7.ZA(Unknown Source)
	at burp.Zgc4.Zf(Unknown Source)
	at burp.Zgce.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by GeorginaReeder** [comment]
Thanks for bringing this to our attention @badboycxcc , we'll look into it!
